export interface RegisterFilter { multiply?: number; offset?: number; round?: number; firmware_version?: number; [key: string]: unknown }
export interface Register { id: string; name: string; address: number; register_type: string; unit_of_measurement: string; state_class: string; device_class: string; value_type: string; filters: RegisterFilter[]; passthrough?: Record<string, unknown>; tested?: boolean; testResult?: string; testError?: string }
export interface BaudrateConfig { address: number; possible_baudrates: Record<string, number> }
export interface SetBase { set_address_address?: number; set_baudrate?: BaudrateConfig }
export interface OutputRegister { name: string; address: number; unit_of_measurement?: string; state_class?: string; device_class?: string; value_type: string; filters?: RegisterFilter[]; [key: string]: unknown }
export interface OutputRegisterBlock { base: number; length: number; register_type?: string; update_every_n?: number; registers: OutputRegister[] }
export interface DeviceConfig { model: string; manufacturer?: string; description?: string; category?: string; default_address?: number; default_update_interval?: string; set_base?: SetBase; registers_base: OutputRegisterBlock[]; [key: string]: unknown }
export interface CreatorState { modelName: string; fileName: string; category: string; manufacturer: string; description: string; defaultAddress: number; defaultUpdateInterval: string; enableSetAddress: boolean; setAddressAddress: number; enableSetBaudrate: boolean; baudrateAddress: number; baudrateMappings: Record<string, number>; registers: Register[]; passthrough: Record<string, unknown>; importedBlocks: OutputRegisterBlock[] | null }
export const CATEGORIES = [{ value: 'sensors', label: 'Sensors' }, { value: 'energy_meters', label: 'Energy Meters' }, { value: 'hvac', label: 'HVAC' }, { value: 'inverters', label: 'Inverters' }, { value: 'other', label: 'Other' }];
export const VALUE_TYPES = ['U_WORD', 'S_WORD', 'U_DWORD', 'S_DWORD', 'U_DWORD_R', 'S_DWORD_R', 'U_QWORD', 'S_QWORD', 'U_QWORD_R', 'FP32', 'FP32_R'];
export const DEVICE_CLASSES = ['', 'temperature', 'humidity', 'voltage', 'current', 'power', 'energy', 'frequency', 'distance', 'pressure', 'speed']; export const STATE_CLASSES = ['measurement', 'total', 'total_increasing']; export const REGISTER_TYPES = ['holding', 'input']; export const UNITS_OF_MEASUREMENT = ['', '°C', '%', 'V', 'A', 'W', 'kW', 'VA', 'kVA', 'var', 'kvar', 'kWh', 'kvarh', 'Hz', 'mm', 'cm', 'm³/h', 'L', 'min', 'Ohm', '°'];
export const generateId = () => Math.random().toString(36).substring(2, 9); export const STORAGE_KEY = 'modbus_device_creator_draft';
const top = new Set(['model','manufacturer','description','category','default_address','default_update_interval','set_base','registers_base']); const regFields = new Set(['name','address','unit_of_measurement','state_class','device_class','value_type','filters']); const type = 'input';
export const emptyCreatorState = (): CreatorState => ({ modelName:'',fileName:'',category:'sensors',manufacturer:'',description:'',defaultAddress:1,defaultUpdateInterval:'30s',enableSetAddress:false,setAddressAddress:256,enableSetBaudrate:false,baudrateAddress:257,baudrateMappings:{'9600':9600,'19200':19200},registers:[],passthrough:{},importedBlocks:null });
export const parseDeviceConfig = (config: DeviceConfig): CreatorState => { const state=emptyCreatorState(); state.modelName=config.model; state.manufacturer=config.manufacturer??''; state.description=config.description??''; state.category=config.category??state.category; state.defaultAddress=config.default_address??1; state.defaultUpdateInterval=config.default_update_interval??'30s'; Object.entries(config).forEach(([k,v])=>{if(!top.has(k))state.passthrough[k]=v}); if(config.set_base?.set_address_address!==undefined){state.enableSetAddress=true;state.setAddressAddress=config.set_base.set_address_address} if(config.set_base?.set_baudrate){state.enableSetBaudrate=true;state.baudrateAddress=config.set_base.set_baudrate.address;state.baudrateMappings=config.set_base.set_baudrate.possible_baudrates} config.registers_base.forEach(b=>b.registers.forEach(r=>{const passthrough:Record<string,unknown>={};Object.entries(r).forEach(([k,v])=>{if(!regFields.has(k))passthrough[k]=v});state.registers.push({id:generateId(),name:r.name,address:r.address,register_type:b.register_type??type,unit_of_measurement:r.unit_of_measurement??'',state_class:r.state_class??'',device_class:r.device_class??'',value_type:r.value_type,filters:r.filters??[],...(Object.keys(passthrough).length?{passthrough}:{})})}));state.importedBlocks=config.registers_base;return state };
export const getRegisterSize=(value:string)=>['U_DWORD','S_DWORD','U_DWORD_R','S_DWORD_R','FP32','FP32_R'].includes(value)?2:['U_QWORD','S_QWORD','U_QWORD_R'].includes(value)?4:1;
export const groupRegistersIntoBlocks=(registers:Register[]):OutputRegisterBlock[]=>{const types:Record<string,Register[]>={};registers.forEach(r=>(types[r.register_type]??=[]).push(r));return Object.entries(types).flatMap(([register_type,rs])=>{const groups:Register[][]=[];[...rs].sort((a,b)=>a.address-b.address).forEach(r=>{const g=groups[groups.length-1];const previous=g?.[g.length-1];if(!g||r.address-(previous!.address+getRegisterSize(previous!.value_type))>10)groups.push([r]);else g.push(r)});return groups.map(g=>{const last=g[g.length-1];return {base:g[0].address,length:last.address-g[0].address+getRegisterSize(last.value_type),register_type,registers:g.map(r=>({name:r.name,address:r.address,value_type:r.value_type,...(r.unit_of_measurement?{unit_of_measurement:r.unit_of_measurement}:{}),...(r.state_class?{state_class:r.state_class}:{}),...(r.device_class?{device_class:r.device_class}:{}),...(r.filters.length?{filters:r.filters}:{}),...(r.passthrough??{})}))}})})};
const signature=(bs:OutputRegisterBlock[])=>bs.flatMap(b=>b.registers.map(r=>`${b.register_type??type}:${r.address}`)).sort().join('|');
export const buildRegistersBase=(registers:Register[], imported:OutputRegisterBlock[]|null)=>{const generated=groupRegistersIntoBlocks(registers);if(!imported||signature(imported)!==signature(generated))return generated;const index=new Map(generated.flatMap(b=>b.registers.map(r=>[`${b.register_type??type}:${r.address}`,r] as const)));return imported.map(b=>({...b,registers:b.registers.map(r=>index.get(`${b.register_type??type}:${r.address}`)??r)}))};
export const buildDeviceConfig=(s:CreatorState):DeviceConfig=>{const config:DeviceConfig={model:s.modelName,registers_base:buildRegistersBase(s.registers,s.importedBlocks),...s.passthrough};if(s.manufacturer)config.manufacturer=s.manufacturer;if(s.description)config.description=s.description;if(s.category)config.category=s.category;if(s.defaultAddress)config.default_address=s.defaultAddress;if(s.defaultUpdateInterval)config.default_update_interval=s.defaultUpdateInterval;if(s.enableSetAddress||s.enableSetBaudrate)config.set_base={...(s.enableSetAddress?{set_address_address:s.setAddressAddress}:{}),...(s.enableSetBaudrate?{set_baudrate:{address:s.baudrateAddress,possible_baudrates:s.baudrateMappings}}:{})};return config};
